name: ETL Pipeline CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  etl-pipeline:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: etlpass
          POSTGRES_DB: etl_db
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dbt-postgres

      - name: Wait for Postgres
        run: sleep 10

      - name: Run Python ETL
        run: python etl/extract_and_load.py

      - name: Set up dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "etl_dbt:" > ~/.dbt/profiles.yml
          echo "  target: dev" >> ~/.dbt/profiles.yml
          echo "  outputs:" >> ~/.dbt/profiles.yml
          echo "    dev:" >> ~/.dbt/profiles.yml
          echo "      type: postgres" >> ~/.dbt/profiles.yml
          echo "      host: localhost" >> ~/.dbt/profiles.yml
          echo "      user: postgres" >> ~/.dbt/profiles.yml
          echo "      password: etlpass" >> ~/.dbt/profiles.yml
          echo "      port: 5433" >> ~/.dbt/profiles.yml
          echo "      dbname: etl_db" >> ~/.dbt/profiles.yml
          echo "      schema: raw" >> ~/.dbt/profiles.yml
          echo "      threads: 1" >> ~/.dbt/profiles.yml

      - name: Run dbt
        working-directory: ./dbt/etl_dbt
        run: |
          dbt deps
          dbt run
          dbt test

      - name: Upload logs (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dbt-logs
          path: dbt/etl_dbt/logs
